language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "6.7"

sudo: false

cache:
  directories:
  - node_modules

before_install:
  - npm config set strict-ssl false
  - npm install coveralls

after_success:
  - npm run coverage

before_script:
  # we only need to run eslint once per build, so let's conserve a few resources
  - 'if [ "x$TRAVIS_NODE_VERSION" = "x6.7" ]; then $(npm bin)/eslint .; fi'

git:
  depth: 1
